version: "3.9"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: es01
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "TZ=Asia/Tokyo"
    ports:
      - 9200:9200
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - "TZ=Asia/Tokyo"
      - I18N_LOCALE="ja-JP"
    depends_on:
      - es01
    restart: always
